language: node_js
node_js:
  - 6

install:
 - npm install grunt
 - npm install grunt-cli
 - npm install

before_script: grunt build

after_success:
 - cd dist
 - zip -r bsis-frontend.zip * >/dev/null

deploy:
  provider: releases
  api_key: 
    secure: "NHO6NdUUU6tvAqRFFLxB6+7TY7keGo/1xcEQSA1WqanKvg1MlFeeu/XDlKYpfCNDpaHenn+u9XrwarPcUp3iaOU6NtIUq0FYwPgp7dV17HkgLnhRxG1l6/don8tZuuxwDE2k5hUPuN3rXZzqpsf1KaXwBnoE2sYCnwuBf4f60PzF3CzVeicGFWafSPWDErVd5fubce1WbPKYtHiwyWvEDJRp6pPAVhohwIHhWgDX0Znc7zL8lAC359ucjGsm4KAOQYTUPkHHLO/w4jP65j3/8ukf7XbW3jPB4DaFgt7vqRpmPZL2OVmn1IHUWeKUGdeCwCrw9toIe3T6R0CnK82CvsaTRb4Weqr5xER6cHKUzLGqj1yhXwuNCbLtPyFDNs7nHtS95X6R0QvX3Juu5wzNrfll06JAjSBm703k8ucYAs/T+f5pLSH9kIzTrWZQx5vj9Ozvb94RP4d7LiTOZyGnlHy/2erxoEH/ugEuMthmSSZxL4B/F9jdToKIseH3NaHWOXAFqnZpcpTSN8V1Q/oaCXcSW7QY+/0RTRojuADkb3ukUUX3lyadZgeJKCCckKyo0CKmfd19p7ZNMEhYneK2EQ2+fVpvOFiN2pJWwVMU96H2VG9LF6YxgGs4wCxesjT9T7GEoP5W4819w8wje4mVs5gkJ2eTuRMmd26KeP37qZQ="
  file: "$TRAVIS_BUILD_DIR/dist/bsis-frontend.zip"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
