language: node_js
node_js:
  - 6

install:
 - npm install grunt
 - npm install grunt-cli
 - npm install

before_script: grunt build

after_success:
 - cd dist
 - zip -r bsis-frontend.zip * >/dev/null

deploy:
  provider: releases
  api_key: "47a92f9761a055720a1b35ec021db098d6a2e2d1"
  file: "$TRAVIS_BUILD_DIR/dist/bsis-frontend.zip"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
