language: node_js
node_js:
  - 4
  - 5
  - 6
branches:
  only:
    - master
    - develop
    - /^release\/
    - /^support\/
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
