# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.box = "precise32"
	config.vm.box_url = "http://files.vagrantup.com/precise32.box"

	config.vm.network :bridged
	config.vm.forward_port 9000, 9000

	config.vm.share_folder "bsis-frontend", "/bsis-frontend", "../../../"

	config.vm.provision :shell do |shell|
		shell.inline = "mkdir -p /etc/puppet/modules;
			puppet module install willdurand/nodejs"
	end

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "./"
		puppet.manifest_file  = "bsis-frontend.pp"
	end
end